services:
  postgres:
    image: postgres:11
    environment:
      - POSTGRES_USER=kong
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-kong}
      - POSTGRES_DB=kong
    ports:
      - 5432:5432
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - kong-net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d kong -U $${POSTGRES_PASSWORD:-kong}"]
      start_period: 20s
      interval: 30s
      retries: 5
      timeout: 5s
  #########################
  kong-migrate:
    image: kong/kong-gateway:3.7.1.2
    command: kong migrations bootstrap
    restart: on-failure
    environment:
      - KONG_DATABASE=postgres
      - KONG_PG_HOST=postgres
      - KONG_PG_DATABASE=kong
      - KONG_PG_PASSWORD=${POSTGRES_PASSWORD:-kong}
      - KONG_PASSWORD=${KONG_PASSWORD:-P@ssw0rd}
    networks:
      - kong-net
    depends_on:
      - postgres
  kong:
    image: kong/kong-gateway:3.7.1.2
    environment:
      - KONG_DATABASE=postgres
      - KONG_PG_HOST=postgres
      - KONG_PG_USER=kong
      - KONG_PG_PASSWORD=${POSTGRES_PASSWORD:-kong}
      - KONG_PROXY_ACCESS_LOG=/dev/stdout
      - KONG_ADMIN_ACCESS_LOG=/dev/stdout
      - KONG_PROXY_ERROR_LOG=/dev/stderr
      - KONG_ADMIN_ERROR_LOG=/dev/stderr
      - KONG_ADMIN_LISTEN=0.0.0.0:8001
      - KONG_ADMIN_LISTEN_SSL=0.0.0.0:8443
      - KONG_ADMIN_GUI_URL=http://localhost:8002
    ports:
      - 80:8000
      - 8001:8001
      - 8002:8002
      - 443:8443
    networks:
      - kong-net
    depends_on:
      - postgres
    restart: on-failure
    healthcheck:
      test: ["CMD", "kong", "health"]
      interval: 30s
      retries: 5
      timeout: 5s
  #######################
  konga-migrate:
    image: pantsel/konga:0.14.7
    command: "-c prepare -a postgres -u postgresql://kong:${POSTGRES_PASSWORD:-kong}@postgres:5432/konga"
    networks:
      - kong-net
    restart: on-failure
    depends_on:
      - postgres
  konga:
    image: pantsel/konga:0.14.7
    environment:
      - TOKEN_SECRET=${KONGA_SECRET:-P@ssw0rd}
      - DB_ADAPTER=postgres
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=kong
      - DB_PASSWORD=${POSTGRES_PASSWORD:-kong} 
      - DB_DATABASE=konga
    ports:
      - 1337:1337
    networks:
      - kong-net
    depends_on:
      - postgres
volumes:
  pgdata:
    driver: local
networks:
  kong-net:
